// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHerois.Data;

namespace SuperHerois.Migrations
{
    [DbContext(typeof(SuperHeroisContext))]
    [Migration("20200521224151_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SuperHerois.Models.SuperHeroi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fraqueza");

                    b.Property<string>("nome");

                    b.Property<string>("poder");

                    b.HasKey("id");

                    b.ToTable("SuperHeroi");
                });
#pragma warning restore 612, 618
        }
    }
}
